sudo: false

language: ruby
rvm:
- 2.6

cache: bundler

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # Required to avoid TLS errors

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
  - set -e # halt script on error
  - bundle exec jekyll build
# ignore blablacar as they are blocking non browser clients
  - bundle exec htmlproofer --url-ignore https://www.blablacar.de ./_site
